spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fangzongzhou/config-repo.git
          username: fangzongzhou
          password: fangzongzhougithub
server:
  port: 1201
